# -*- org-list-allow-alphabetical: t; -*-
#+TITLE: Potenser och logaritmer
#+DATE:
#+AUTHOR: Jesper larsson \enspace \textit{v. 1.0 (aug. 2017)}
#+LANGUAGE: sv
#+LATEX_COMPILER: lualatex
#+OPTIONS: toc:nil ^:{} broken-links:mark num:0
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[swedish]{babel}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont[Ligatures=TeX]{Linux Libertine O}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER_EXTRA: \frenchspacing

* Potens/exponentiering

En /potens/ i matematiken skrivs $x^{n}$, (/$x$ upphöjt till $n$/) där
$x$ kallas /basen/ och $n$ /exponenten/. Sådan /exponentiering/ är en kortform
för upprepad multiplikation:

\[x^n = \underbrace{x \cdot x \cdot x\cdot \quad \cdots \quad \cdot x}_{n\text{ stycken }x}\]

Direkt av definitionen följer (kontrollera varför det blir så genom att skriva om potenserna som
upprepad multiplikation):
\[x^n \cdot x^m = x^{n+m}\]
och
\[\dfrac{x^n}{x^m} = x^{n-m}\]  

För bekvämlighets skull utvidgar vi definitionen till exponenter
mindre än ett: $x^0 = 1$ för alla $x$ utom $0$, och $x^{-n} = 1 /
x^n$ (kontrollera att det funkar i formlerna).

Exponenten behöver inte vara ett heltal heller. Enligt vad vi redan sagt bör vi
ha $x^{1/2} \cdot x^{1/2} = x^{1/2 + 1/2} = x$. Det uppfylls bara om vi
definierar $x^{1/2} = \sqrt{x}$. Enligt samma argument är $x^{1/3} =
\sqrt[3]{x}$.

* Logaritm

/Logaritmering/ är motsatsen till exponentiering. Vi definierar logaritmen i bas
$b$, 
$b\text{\emph{-logaritmen}}$, av $x$ som det tal $n$ som gör att $b^{n}=x$. Alltså:
\[\log_b x = n \qquad \Longleftrightarrow \qquad b^n = x\]

Memorera det!
(Med andra ord: $b^{log_b x} = x$, tänk efter varför det säger samma sak.)

Ett mer handfast sätt att förklara logaritm är följande: om
man börjar med $x$, delar med $b$, sedan delar resultatet av det med $b$, och
fortsätter att dela med $b$ tills man får $1$, 
så är $\log_b x$ antalet divisioner man har utfört. Det funkar
dock bara om $x$ är en potens av $b$, alltså $x=b^n$ för något heltal $n$, annars
kommer man aldrig exakt till $1$.  (Tänk efter varför den här förklaringen
stämmer med definitionen.)

** Tvålogaritm

   De flesta har antagligen stött på /tiologaritmen/ (intressant för att tio är
basen i vårt vanliga talsystem) och den /naturliga logaritmen/, med
basen $e \approx 2.71828$ (intressant därför att $x^e$, /exponentialfunktionen/,
har speciella matematiska egenskaper). Men när vi datavetare talar om logaritm
menar vi nästan alltid /tvålogaritmen/ (eller ibland någon logaritm vilken som
helst). Därför definierar vi en kortform för $2\text{-logaritmen}$:
\[\lg x = \log_2 x\]
Det är inte alla som använder $\lg$ som $\log_2$, men vår kursbok och många
andra gör det.

När $x$ är en potens av två (alltså $x = 2^n$ för något heltal $n$),
är $\lg x$ ett heltal. Men vi behöver inte begränsa $\lg x$ med att kräva att $x$
en potens av två: enligt vad vi sagt ovan är ju till exempel $2^{1/2} =
\sqrt{2}$, så $\lg \sqrt{2}
= 1/2$.

** Avrundning

Den generella definitionen av logaritmer för positiva tal hoppar vi över,
men vi kan behöva resonera om /mellan/ vilka värden de måste ligga. Om a, b och
c är tre positiva tal sådana att $a < b < c$ så gäller också $\lg a < \lg b
< \lg c$ (tänk efter varför). Är vi till exempel intresserade av värdet på $\lg 10$ är kan vi
konstatera att $2^3 < 10 < 2^4$, och att $\lg 10$ därför måste vara ett tal
mellan $3$ och $4$. Ofta kan vi nöja oss så, och använda den här
notationen för att avrunda upp eller ner:
\begin{align*}
\lfloor x \rfloor: & \quad \text{\emph{golvet} av $x$: det största heltalet $ \le x$ \enskip (avrundning nedåt)} \\
\lceil x \rceil: & \quad \text{\emph{taket} av $x$: det minsta heltalet $ \ge x$ \enskip (avrundning uppåt)}
\end{align*}
Så exempelvis är $\lfloor \lg 10 \rfloor = 3$ och $\lceil \lg 10 \rceil = 4$.

** Viktiga logaritmlagar

Följande formler följer av definitionen av logaritm (här anges ingen bas för logaritmerna eftersom formlerna gäller oavsett vilken
logaritm man menar):
\begin{eqnarray*}
  \log (x\cdot y) &=& \log x + \log y \\
  \log x^y &=& y\log x
\end{eqnarray*}
Försök att själv klura ut varför det blir så, och memorera sedan dessa
lagar.De är mycket användbart att kunna utantill för att snabbt kunna använda
till att se samband.

** Basbyte

En sista viktig formel: eftersom $x = a^{\log_a x}$:
\[\log_b x = \log_b a^{\log_a x} = (\log_b a)\cdot (\log_a x)\]
Det betyder, eftersom $\log_b a$ är en konstant som bara beror på $a$ och $b$,
att logaritmer i olika baser bara skiljer sig åt med en konstant faktor, alltså
\[\log_b x = k\cdot \log_a x\]
där $k$ är en konstant som bestäms av $a$ och $b$.

Exempelvis är $\lg x \approx 3,32\cdot\log_{10}x$ (vilket innebär att ett tal i
det binära talsystemet får ungefär $3,32$ gånger fler siffror än samma tal i det vanliga decimala).

I algoritmanalysjargong kan man uttrycka det så att alla logaritmer
/asymptotiskt växer lika snabbt/. Därför kan man ibland nöja sig med att säga
$\log$ utan att specificera basen.





