# -*- org-list-allow-alphabetical: t; -*-
#+TITLE: Summanotation och några viktiga summor
#+DATE:
#+AUTHOR: Jesper Larsson \ensp /v. 1.1 (aug. 2020)/
#+LANGUAGE: sv
#+LATEX_COMPILER: lualatex
#+OPTIONS: toc:nil ^:{} broken-links:mark num:0
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[swedish]{babel}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont[Ligatures=TeX]{Linux Libertine O}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage[textwidth=14cm]{geometry}
#+LATEX_HEADER_EXTRA: \frenchspacing

* Notation

”Stora-sigma-notationen” för summor kan verka respektingivande för ovana matematikläsare, men den är inget
annat än matematikens sätt att skriva något som i de flesta programspråk skulle ha
varit en /for/-loop. Under summatecknet står /loopvariabel = startvärde/,
ovanpå står /slutvärde/, och till höger står uttrycket för varje term i
summan. Termen brukar innehålla loopvariabeln någonstans, så att värdena av termerna
blir olika. Exempel:
\[\sum_{i=5}^{10} 2i \; = \underbrace{2\cdot5}_{\text{första
termen}}\!+\!\underbrace{2\cdot6}_{\text{andra
termen}} \hspace{-.67em} \mathop+ 2\cdot7+2\cdot8+2\cdot9+\hspace{-.33em}\underbrace{2\cdot10}_{\text{sista termen}} \;
= \; 90\]

I löpande tryckt text brukar texten under och över
summatecknet vara framflyttad för att inte ta så mycket plats i höjdled, så att
det till exempel ser ut så här: $\sum_{i=5}^{10} 2i$.

Mer generellt, om vi kallar term nummer $i$ för $t_i$ så är:
\[\sum_{i=a}^{b} t_i \; = \; t_{a} + t_{a+1} + t_{a+2} + \cdots + t_{b-1} + t_b\]

En variant är: \[\sum_{i \in S} t_i\] Här utläses tecknet $\in$ som /tillhör/,
och $S$ är en mängd. Vad vi säger är ”summan av $t_i$ för alla $i$ som finns i
$S$”. En mängd kan man ange genom att räkna upp elementen med komma emellan och
omge dem med ”{” och ”}”, så $\sum_{i\in\{a, \ldots, b\}} t_i$ betyder precis
detsamma som $\sum_{i=a}^{b} t_i$. Ytterligare ett sätt att skriva samma sak är
$\sum_{i=a\ldots b} t_i$.

Om det är tydligt av sammanhanget vilka olika värden $i$ kan anta kan man till
och med skriva bara $\sum_i t_i$, med betydelsen ”summan av $t_i$ för alla $i$”. 

* Heltal från $1$ till $N$

Ett plus två plus tre, och så vidare, upp till $N$, alltså $1+2+3+\cdots + N$:

\[\sum_{i=1}^N i \; =\; \frac{N(N+1)}{2}\]

Varför är summan $N(N+1)/2$? Här är ett sätt att se det: Gå nerifrån och upp i
följande figur, och lägg samman de fyllda cirklarna rad för rad. Som synes blir
det  $1+2+3+\cdots + N$ stycken. 

|   $N$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ |
| $N-1$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   |
| $N-2$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     2: | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     1: | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     0: | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|    <r> |           |           |           |           |           |           |           |           |

Det finns $N+1$ rader med $N$ cirklar (fyllda eller ej) i varje, alltså totalt
$N(N+1)$. Precis hälften av dem är fyllda,
alltså $N(N+1)/2$. 

Om man föredrar ett algebraiskt bevis: Börja med fallet att $N$ är ett jämnt
tal. Gruppera ihop termerna i par. Den första, $1$, paras ihop med den sista,
$N$. Den
näst första, $2$, med den näst sista, $N-1$, och så vidare:
\[
\sum_{i=1}^N i \; =\;
(1+N)  + 
(2\; + \; N\!-\! 1)  + 
(3\; + \; N\!-\! 2)  + \;\cdots\; \]

Varje parentes i detta uttryck har samma värde, $N+1$, och antalet parenteser är
hälften så många som de ursprungliga ogrupperade termerna, alltså $N/2$. Multiplicerar vi ihop
det får vi $N(N+1)/2$.

\smallskip

\noindent *Övning* /Modifiera resonemanget till att gälla udda $N$ istället, och visa att summan även då är $N(N+1)/2$./

\smallskip

Ett annat sätt att skriva $N(N+1)/2$ är $\frac{1}{2}N^2 + \frac{1}{2}N$. I
algoritmanalys struntar vi normalt i alla termer utom den som har högst exponent
på $N$, eftersom de är försvinnande små när $N$ är stort. Vi nöjer oss
alltså nästan alltid med att konstatera att
\[\sum_{i=1}^N i \; \sim\; \frac{1}{2}N^2\]
Ofta kan vi dessutom strunta i konstanten framför $N^2$, och nöja oss med att säga att summan
växer med $N^2$ – med andra ord att summan är /kvadratisk i $N$/. Vi kan till och med
nöja oss med att summan är /högst/ kvadratisk i $N$, och säga att summan är
$O(N^2)$, vilket utläses /ordo $N^2$/.

* Stigande tvåpotenser

Ett plus två plus fyra plus åtta, och så vidare upp till $N$. Varje term,
inklusive den sista $N$, är då en
potens av två, så vi kan säga att $N=2^k$ för något hektal $k$, eller med andra ord
$k=\lg N$. Summan har då $k+1$ termer:
\[\sum_{i=0}^k 2^i \; =\; 2\cdot 2^k-1 \; =\; 2N-1\]
Varför är summan $2N-1$? Vi kan testa med några rimligt små $k$ och se att det
stämmer, till exempel: $1+2+4+8+\cdots+64 = 127$. Då vet vi att vi är på rätt
spår, men det är inget bevis. Hur kan vi veta att det
gäller alltid? Det visar vi lättast med ett /induktionsbevis/. Vi visar först
att det stämmer i basfallet $k=0$. Summan får då en enda term:
\[\sum_{i=0}^0 2^i \; =\; 2^0 \; =\; 1\]

Och $2\cdot 2^0-1=2\cdot 1-1=1$, stämmer!

Sedan visar vi att /om/ likheten
gäller för $k$ så gäller den också för $k+1$, för varje icke-negativt värde på $k$. Då har vi indirekt visat att den
också gäller för $k=0+1=1$, $k=1+1=2$, $k=2+1=3, och så vidare. Det är som att visa att vi kan
klättra upp för en hel stege, oavsett hur hög den är, genom att visa att vi kan komma till första pinnen,
och att om vi kan komma till pinne $k$ kan vi också komma till pinne $k+1$.

Vi antar alltså att likheten stämmer för $k$, alltså att det är sant att $\sum_{i=0}^k 2^i =
2\cdot 2^k-1$. Sedan tittar vi på likheten med $k$ utbytt mot $k+1$ och försöker
visa att /om/ antagandet stämmer så stämmer också den, alltså att
$\sum_{i=0}^{k+1} 2^i = 2\cdot 2^{k+1}-1$.

Vi
lösgör den sista termen ur summan, och använder att vi enligt antagandet redan
vet vad summan av termerna före den är:
\[\sum_{i=0}^{k+1} 2^i = \underbrace{\left(\sum_{i=0}^{k} 2^i \right)}_{2\cdot
2^k-1} \mathop+ 2^{k+1} =
\underbrace{\,2\cdot 2^k}_{2^{k+1}} \mathop- 1 + 2^{k+1} = 2\cdot 2^{k+1}-1\]
Klart!
* Avtagande tvåpotenser

En summa med ett /ändligt/ antal termer, som de vi hanterat hittills, är förstås
ändlig. Lägger vi ihop ett /oändligt/ antal termer blir summan oändlig – eller?
Faktiskt inte alltid: om termerna blir mindre och mindre, och om de
blir mindre /tillräckligt snabbt/, så /konvergerar/ summan och blir ändlig.

En summa som konvergerar är en halv plus en fjärdedel plus en åttondel och så vidare i all oändlighet:
\[\sum_{i=1}^{\infty} \frac{1}{2^i} = 1\]
Summan kan också skrivas $\sum_{i=1}^{\infty} 2^{-i}$.

Varför är summan $1$? För att visa det, tänk istället att vi börjar från $1$ och
drar bort termerna en efter en, så kan vi se att vi kommer närmare och närmare
noll, men aldrig till något som är mindre än noll: Först drar vi bort en halv,
då har vi en halv kvar. Sedan drar vi bort en fjärdedel, vilket är hälften av en
fjärdedel, och vi har en fjärdedel kvar. Sedan drar vi bort en åttondel, vilket
är hälften av en fjärdedel och så vidare – vi kommer att fortsätta att dra bort
hälften av det vi har kvar i all oändlighet, men det tar oändligt många steg att
komma ner till noll.

Ett annat sätt att visa att detta stämmer: börja med $1$, dela upp i två halvor,
och fortsätt sedan dela upp den sista termen i halvor i all oändlighet:
\[\begin{split}
1 \; &=\; \frac{1}{2} + \frac{1}{2} \;=\; \frac{1}{2} +\frac{1}{4} +
\frac{1}{4} \;=\; \frac{1}{2} + \frac{1}{4} +
\frac{1}{8}+ \frac{1}{8} \;=\; \\
&=\; \frac{1}{2} + \frac{1}{4} +
\frac{1}{8}+ \frac{1}{16}+ \frac{1}{16} \;=\; \cdots \;=\; \sum_{i=1}^{\infty} \frac{1}{2^i}
\end{split}\]


