# -*- org-list-allow-alphabetical: t; -*-
#+TITLE: Summor
#+LANGUAGE: sv
#+LATEX_COMPILER: lualatex
#+OPTIONS: toc:nil ^:{} broken-links:mark num:0
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[swedish]{babel}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont[Ligatures=TeX]{Linux Libertine O}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER_EXTRA: \frenchspacing

* Notation

”Stora-sigma-notationen” för summor kan se imponerande ut, men den är inget
annat än matematikens sätt att skriva vad som i de flesta programspråk skulle ha
varit en /for/-loop. Under summatecknet står /loopvariabel = startvärde/,
ovanpå står /slutvärde/, och till höger står uttrycket för varje term i
summan. Termen innehåller normalt loopvariabeln någonstans, så att värdena av termerna
blir olika för olika. Exempel:
\[\sum_{i=5}^{10} 2i \; = \; \underbrace{2\cdot5}_{\text{första
termen}}\!+\!\underbrace{2\cdot6}_{\text{andra
termen}} \!\! + \: 2\cdot7+2\cdot8+2\cdot9+\underbrace{2\cdot10}_{\text{sista termen}} \;
= \; 90\]
Det betyder alltså samma sak som värdet av =sum= efter att följande programkod har körts:
\small
#+BEGIN_SRC java
    sum = 0;
    for (i = 5; i <= 10; i++) {
        sum = sum + 2*i;
    }
#+END_SRC
\normalsize

I löpande tryckt text brukar texten under och över
summatecknet vara framflyttad för att inte ta så mycket plats i höjdled, så att
det till exempel ser ut så här: $\sum_{i=5}^{10} 2i$.

Mer generellt, om vi kallar term nummer $i$ för $t_i$, så är:
\[\sum_{i=a}^{b} t_i \; = \; t_{a} + t_{a+1} + t_{a+2} + \cdots + t_{b-1} + t_b\]

En variant är:
\[\sum_{i \in S} t_i\]
Här utläses tecknet $\in$ som /tillhör/ eller /i/, och $S$ är en mängd. Summan får en
term för vart och ett av elementen i $S$. Det motsvarar alltså /for/-loopen som
skrivs ”\verb'for (i : S)'” i Java och ”\verb'for (i in S)'” i en del andra
språk. En mängd kan man ange genom att räkna upp elementen med komma emellan och
omge dem med ”{” och ”}”, så $\sum_{i\in\{a, \ldots, b\}} t_i$ betyder precis
detsamma som $\sum_{i=a}^{b} t_i$. Ytterligare ett sätt att skriva samma sak är
$\sum_{i=a\ldots b} t_i$.

Om det är tydligt av sammanhanget vilka olika värden $i$ kan anta kan man till
och med skriva bara $\sum_i t_i$, med betydelsen ”summan av $t_i$ för alla $i$”. 

* Heltal från $1$ till $N$

Ett plus två plus tre, och så vidare, upp till $N$, $1+2+3+\cdots + N$:

\[\sum_{i=1}^N i \; =\; \dfrac{N(N+1)}{2}\]

Varför är summan $N(N+1)/2$? Vi kan tänka oss $N+1$ rader av $N$ cirklar. I första raden är
alla fyllda, i andra raden alla utom en, och så vidare, och i sista raden är
ingen fylld.

|   $N$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ |
| $N-1$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   |
| $N-2$: | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|        | $\bullet$ | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     2: | $\bullet$ | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     1: | $\bullet$ | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|     0: | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   | $\circ$   |
|    <r> |           |           |           |           |           |           |           |           |

Summan vi är ute efter är lika med antalet fyllda cirklar. Det totala antalet
cirklar (fyllda och tomma) är $N(N+1)$, och precis hälften av dem är tomma.

Eller om man föredrar ett algebraiskt bevis: Anta först att $N$ är ett jämnt
tal. Gruppera ihop termerna i par: den första, $1$, med den sista, $N$; den
näst första, $2$, med den näst sista, $N-1$, och så vidare:
\[
\sum_{i=1}^N i \; =\;
(1+N)  + 
(2\: + \: N\!-\! 1)  + 
(3\: + \: N\!-\! 2)  + \;\cdots\; \]

Varje parentes i detta uttryck har värdet $N+1$, och antalet parenteser är
hälften så många som termerna ogrupperade, alltså $N/2$. Multiplicerar vi ihop
det får vi $N(N+1)/2$.

\smallskip

\noindent *Övning 1* /Visa med ett algebraiskt resonemang att summan blir
$N(N+1)/2$ även när $N$ är udda./

\smallskip

Ett annat sätt att skriva $N(N+1)/2$ är $\frac{1}{2}N^2 + \frac{1}{2}N$. I
algoritmanalys struntar vi normalt i alla termer utom den som har högst exponent
på $N$, eftersom de blir försvinnande små när $N$ blir stort. Vi nöjer oss
alltså nästan alltid med att konstatera att
\[\sum_{i=1}^N i \; \sim\; \dfrac{1}{2}N^2\]
Ofta kan vi dessutom strunta i konstanten framför $N^2$, och nöja oss med att säga att summan
växer med $N^2$, eller med andra ord är /kvadratisk i $N$/. Vi kan till och med
ofta nöja oss med att summan är /högst/ kvadratisk i $N$, vilket är vad
uttrycket $O(N^2)$ betyder (utläses /ordo $N^2$/).

* Avtagande tvåpotenser

En summa med ett /ändligt/ antal termer, som de vi hanterat hittills, är förstås
ändlig. Lägger vi ihop ett oändligt antal termer blir summan oändlig. Eller?
Faktiskt inte alltid: om termerna blir mindre och mindre efter hand, och om de
blir mindre /tillräckligt snabbt/, så /konvergerar/ summan och blir ändlig.

E halv plus en fjärdedel plus en åttondel och så vidare i all oändlighet är en
sådan summa som konvergerar:
\[\sum_{i=1}^{\infty} \dfrac{1}{2^i} = 1\]
Summan kan också skrivas $\sum_{i=1}^{\infty} 2^{-i}$.

Varför är summan $1$? För att visa det, tänk istället att vi börjar med $1$ och
drar bort termerna en efter en, så ser vi att vi kommer närmare och närmare
noll, men aldrig till något som är mindre än noll. Först drar vi bort en halv,
då har vi en halv kvar. Sedan drar vi bort en fjärdedel, vilket är hälften av en
fjärdedel, och vi har en fjärdedel kvar. Sedan drar vi bort en åttondel, vilket
är hälften av en fjärdedel och så vidare – vi kommer att fortsätta att dra bort
hälften av det vi har kvar i all oändlighet, men det tar oändligt många steg att
komma till noll, och vi kommer aldrig förbi.

Lite mer matematiskt uttryckt:
\[\begin{split}
1 \; &=\; \dfrac{1}{2} + \dfrac{1}{2} \;=\; \dfrac{1}{2} +\dfrac{1}{4} +
\dfrac{1}{4} \;=\; \dfrac{1}{2} +\dfrac{1}{4} +
\dfrac{1}{8}+ \dfrac{1}{8} \;=\; \\
&=\; \dfrac{1}{2} +\dfrac{1}{4} +
\dfrac{1}{8}+ \dfrac{1}{16}+ \dfrac{1}{16} \;=\; \cdots \;=\; \sum_{i=1}^{\infty} \dfrac{1}{2^i}
\end{split}\]


* Stigande tvåpotenser

Ett plus två plus fyra plus åtta, och så vidare upp till $N$. Varje term blir en
potens av två, så vi kan definiera $k$ så att $N=2^k$, eller med andra ord
$k=\lg N$.
\[\sum_{i=0}^k 2^i \; =\; 2\cdot 2^k-1 \; =\; 2N-1\]
Varför blir det $2-1$? Vi kan testa med några rimligt små $k$ och se att det
stämmer, till exempel: $1+2+4+8+\cdots+64 = 127$. Men hur kan vi veta att det
gäller alltid? Det visar vi lättast med ett /induktionsbevis/: vi visar att det
stämmer i basfallet $k=0$ (trivialt). Sedan visar vi att /om/ det gäller för $k$
så gäller det också för $k+1$. Då har vi indirekt visat att det också gäller för
$k+2$, $k+3$, och så vidare. Det är som att visa att vi kan klättra upp för en
hel stege genom att visa att vi kan komma till första pinnen, och att om vi kan
komma till pinne $k$ kan vi också komma till pinne $k+1$. Då kan det inte finnas
någon pinne vi inte kan komma till.

Vi antar alltså att $\sum_{i=0}^k 2^i = 2\cdot 2^k-1$, och sedan tittar vi på
$\sum_{i=0}^{k+1} 2^i$ och försöker visa att det är $2\cdot 2^{k+1}-1$:
\[\sum_{i=0}^{k+1} 2^i = \underbrace{\left(\sum_{i=0}^{k} 2^i \right)}_{2\cdot
2^k-1} + 2^{k+1} =
\underbrace{\,2\cdot 2^k}_{2^{k+1}} + 2^{k+1} - 1 = 2\cdot 2^{k+1}-1\]
Klart!
